home/urls.py
from django.urls import path, include
from . import views as home_views

app_name = "home"

urlpatterns = [
    path('', home_views.home, name="home"),
    path('pizza-list/', home_views.pizzaList, name="pizza_list"),
    path('pizza-detail/<int:pk>/', home_views.pizzaDetail, name="pizza_detail"),
    path('create-pizza/', home_views.createPizza, name="create_pizza"),
    path('update-pizza/<int:pk>/', home_views.updatePizza, name="update_pizza"),
    path('delete-pizza/<int:pk>/', home_views.deletePizza, name="delete_pizza"),
    path('pizza-size-list/',home_views.pizzaSizeList, name="pizza_size_list"),
    path('create-pizza-size/',home_views.createPizzaSize, name="create_pizza_size"),
    path('toppings-list/',home_views.toppingsList, name="toppings_list"),
    path('create-topping/',home_views.createTopping, name="create_topping"),
]

pizza_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('home.urls')),
]

home/models.py
from django.db import models


class Topping(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class PizzaSize(models.Model):
    size = models.CharField(max_length=50)

    def __str__(self):
        return self.size
    

class Pizza(models.Model):
    default_pizza_type = "Regular"
    pizza_types= (
        (u'regular',"Regular"),
        (u'square',"Square"),
    )
    type = models.CharField(verbose_name="type",choices=pizza_types,max_length=50,blank=False,default=default_pizza_type)

    default_pizza_size = "medium"
    size = models.ForeignKey("PizzaSize", verbose_name="size", on_delete=models.CASCADE,blank=False,default=default_pizza_size)

    toppings = models.ManyToManyField("Topping", verbose_name= "toppings",related_name="pizza")

    def __str__(self):
        return f'{self.type}-{self.size} Pizza'

    def create(self,validated_data):
        return Pizza.objects.create(**validated_data)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

from .models import Topping, PizzaSize, Pizza
from .serializers import ToppingSerializer, PizzaSizeSerializer, PizzaSerializer

from rest_framework.decorators import api_view
from rest_framework.response import Response


@api_view(['GET'])
def home(request):
    api_urls = {
        'Home': '',
        'Pizza List': '/pizza-list/',
        'Pizza Detail': '/pizza-detail/<int:pk>/',
        'Create Pizza': '/create-pizza/',
        'Update Pizza': '/update-pizza/<int:pk>/',
        'Delete Pizza': '/delete-pizza/<int:pk>/',
        'Pizza Size List': '/pizza-size-list/',
        'Create Pizza Size': '/create-pizza-size/',
        'Toppings List': '/toppings-list/',
        'Create Topping': '/create-topping/',
    }
    return Response(api_urls)
    # return render(request,template_name="home/home.html")

@api_view(['GET'])
def pizzaList(request):
    pizzas = Pizza.objects.all()
    serializer = PizzaSerializer(pizzas, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def pizzaDetail(request, pk):
    pizza = Pizza.objects.get(id=pk)
    serializer = PizzaSerializer(pizza, many=False)
    return Response(serializer.data)


@api_view(['POST'])
def createPizza(request):
    serializer = PizzaSerializer(data=request.data)

    if serializer.is_valid(raise_exception=True):
        serializer.save()

    return Response(serializer.data)


@api_view(['POST'])
def updatePizza(request, pk):
    pizza = Pizza.objects.get(id=pk)
    serializer = PizzaSerializer(instance=pizza, data=request.data)

    if serializer.is_valid(raise_exception=True):
        serializer.save()

    return Response(serializer.data)


@api_view(['DELETE'])
def deletePizza(request, pk):
    pizza = Pizza.objects.get(id=pk)
    pizza.delete()
    return Response('Successfully deleted pizza!!!')

@api_view(['GET'])
def pizzaSizeList(request):
    pizzaSizes = PizzaSize.objects.all()
    serializer = PizzaSizeSerializer(pizzaSizes, many=True)
    return Response(serializer.data)

@api_view(['POST'])
def createPizzaSize(request):
    serializer = PizzaSizeSerializer(data=request.data)

    if serializer.is_valid(raise_exception=True):
        serializer.save()

    return Response(serializer.data)


@api_view(['GET'])
def toppingsList(request):
    toppings = Topping.objects.all()
    serializer = ToppingSerializer(toppings, many=True)
    return Response(serializer.data)

@api_view(['POST'])
def createTopping(request):
    serializer = ToppingSerializer(data=request.data)

    if serializer.is_valid(raise_exception=True):
        serializer.save()

    return Response(serializer.data)

home/templates/home/home.html
{% comment %} {% extends "home/home_layout.html" %}

{% block head %}
<h1> Welcome!!!</h1>
{% endblock head %}

{% block body %}
<img src="https://lh3.googleusercontent.com/x9vuyYcmjtnzV351Z1Li5dA1tdjd8EJtieYoekttFu0UfxTvQPqiJnqoh-BFTdCR03EekMBNBx8qaA9a2gWCi5EZQsit=w1000" alt="pizza image" style="width: 90%; height: auto;padding: 5px 50px;" >

<h2>API URLs</h2>
    <p class="pizza-api">
        <ul>
            <li><a href="{% url 'home:pizza_list' %}">List all Pizza</a></li>
            <li><a href="{% url 'home:create_pizza' %}">Create Pizza</a></li> 
        </ul>
    </p>

{% endblock body %}

{% block foot %}
{% endblock foot %} {% endcomment %}

home/templates/home/home_layout.html
{% comment %} {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PIZZA APP</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/main.css' %}">
</head>
<body>
    {% block head %}
    {% endblock head %}

    {% block body %}
    {% endblock body %}

    {% block foot %}
    {% endblock foot %}

</body>
</html> {% endcomment %}